"""
Email delivery module.

Sends via SendGrid when SENDGRID_API_KEY is set, otherwise falls back to SMTP.
All sent emails are persisted to the `emails` table.
"""

import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Literal

from app.core.config import settings
from app.db.session import db_session
from app.db.models import Email

logger = logging.getLogger(__name__)

EmailType = Literal["recommendation", "reminder", "update"]


def _send_via_smtp(to_email: str, subject: str, html_body: str) -> None:
    """Send an email using SMTP (TLS)."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.EMAIL_FROM
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.sendmail(settings.EMAIL_FROM, to_email, msg.as_string())


def _send_via_sendgrid(to_email: str, subject: str, html_body: str) -> None:
    """Send an email using SendGrid HTTP API."""
    try:
        import sendgrid  # type: ignore
        from sendgrid.helpers.mail import Mail  # type: ignore
    except ImportError as exc:
        raise ImportError("Install sendgrid: pip install sendgrid") from exc

    sg = sendgrid.SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
    message = Mail(
        from_email=settings.EMAIL_FROM,
        to_emails=to_email,
        subject=subject,
        html_content=html_body,
    )
    response = sg.send(message)
    if response.status_code >= 400:
        raise RuntimeError(f"SendGrid error {response.status_code}: {response.body}")


def send_email(
    student_id: int,
    to_email: str,
    subject: str,
    html_body: str,
    email_type: EmailType,
) -> dict:
    """
    Send an email and persist the record to the database.

    Returns a dict with keys: success, email_id, error (if any).
    """
    with db_session() as db:
        record = Email(
            student_id=student_id,
            type=email_type,
            subject=subject,
            content=html_body,
            status="pending",
        )
        db.add(record)
        db.flush()  # get record.id
        email_id = record.id

        try:
            if settings.SENDGRID_API_KEY:
                _send_via_sendgrid(to_email, subject, html_body)
            else:
                _send_via_smtp(to_email, subject, html_body)

            record.status = "sent"
            record.sent_at = datetime.utcnow()
            logger.info("Email %s sent to %s (type=%s)", email_id, to_email, email_type)
            return {"success": True, "email_id": email_id}

        except Exception as exc:
            record.status = "failed"
            record.error_message = str(exc)
            logger.error("Email %s failed: %s", email_id, exc)
            return {"success": False, "email_id": email_id, "error": str(exc)}


# ── HTML templates ────────────────────────────────────────────────────────────

def build_recommendation_email(student_name: str, scholarships: list[dict]) -> str:
    rows = "".join(
        f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">
            <strong>{s.get('name', 'Unknown')}</strong><br>
            <small>{s.get('provider', '')} · {s.get('country', '')}</small>
          </td>
          <td style="padding:8px;border-bottom:1px solid #eee">{s.get('amount', 'N/A')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee">{s.get('deadline', 'N/A')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee">
            {round(s.get('match_score', 0) * 100)}%
          </td>
        </tr>
        """
        for s in scholarships
    )
    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
      <h2 style="color:#2563eb">🎓 Your Scholarship Recommendations</h2>
      <p>Hi <strong>{student_name}</strong>,</p>
      <p>Here are your personalised scholarship matches:</p>
      <table width="100%" cellspacing="0" cellpadding="0"
             style="border-collapse:collapse;margin-top:16px">
        <thead>
          <tr style="background:#2563eb;color:#fff">
            <th style="padding:8px;text-align:left">Scholarship</th>
            <th style="padding:8px;text-align:left">Amount</th>
            <th style="padding:8px;text-align:left">Deadline</th>
            <th style="padding:8px;text-align:left">Match</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="margin-top:24px;color:#666;font-size:12px">
        This email was generated by Scholarship Agent. Reply to this email if you need help.
      </p>
    </body></html>
    """


def build_reminder_email(student_name: str, scholarship_name: str, days_left: int) -> str:
    urgency_color = "#dc2626" if days_left <= 7 else "#f59e0b"
    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
      <h2 style="color:{urgency_color}">⏰ Deadline Reminder</h2>
      <p>Hi <strong>{student_name}</strong>,</p>
      <p>The application deadline for <strong>{scholarship_name}</strong> is in
         <strong style="color:{urgency_color}">{days_left} day(s)</strong>.</p>
      <p>Log in to your Scholarship Agent portal to complete your application.</p>
      <p style="margin-top:24px;color:#666;font-size:12px">
        Scholarship Agent · Deadline Tracking Service
      </p>
    </body></html>
    """


def build_update_email(student_name: str, scholarship_name: str, new_status: str) -> str:
    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
      <h2 style="color:#2563eb">📬 Application Update</h2>
      <p>Hi <strong>{student_name}</strong>,</p>
      <p>Your application for <strong>{scholarship_name}</strong> has been updated to:
         <strong>{new_status.upper()}</strong>.</p>
      <p>Log in to your portal to view the details.</p>
    </body></html>
    """
